name: "DateFormatter"
on:
  workflow_dispatch:
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  build-and-test:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ["OS=15.0,name=Apple TV 4K"] #, "OS=15.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
    - uses: szenius/set-timezone@v1.0
      with:
       timezoneMacos: "Europe/Stockholm"
    - uses: actions/checkout@v2
    - name: tvOS - ${{ matrix.destination }}
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme test -destination "${{ matrix.destination }}" clean test | xcpretty
