name: "Testing"
on:
  pull_request:
    branches:
      - '*'
env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
jobs:
  build-and-test:
    runs-on: macos-11
    strategy:
      matrix:
        destination: ["OS=15.0,name=Apple TV 4K"] #, "OS=15.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
    - uses: actions/checkout@v2
    - name: Generate Screenshot
      run: fastlane snapshot
