name: Unit Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && xcodebuild clean -scheme test -destination 'platform="OS=15.0,name=Apple TV 4K"' -derivedDataPath $DERIVED_DATA_PATH build-for-testing
    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme test -destination 'platform="OS=15.0,name=Apple TV 4K"' clean test | xcpretty
