name: Unit Test

on:
  workflow-dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme Viaplay -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' clean test | xcpretty
