name: Unit Test

on:
  workflow_dispatch:

jobs:
  test:
   name: Test
   runs-on: macOS-latest
   strategy:
      matrix:
        destination: ['platform=tvOS Simulator,OS=12.2,name=Apple TV 4K']

   steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && xcodebuild clean -scheme test -destination "${destination}" -derivedDataPath $DERIVED_DATA_PATH build-for-testing
    - name: Run tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme test -destination "${destination}" clean test | xcpretty
